### ISSUE TITLE
Definir diseño y implementación de la banda transportadora

### ISSUE THREAD

**Issue by David05R** [David05R/COLID-BOT#10]
Definir un diseño del montaje de la banda como encargarse de hacer el montaje fisico.

**Comment by JhoelFB123445** [comment]
[https://www.youtube.com/watch?v=8Vnoso8rhaw&ab_channel=Irfan%27sIdioticIdeas ](url)
![Captura de pantalla 2024-09-22 122313](https://github.com/user-attachments/assets/69a94da0-73bd-4a8a-a446-a8d32b5fce59)
